### PR TITLE
Improve errors.

### PR DESCRIPTION
**Pull request by jmjoy**
Using `thiserror` is the most mainstream error handling method in the Rust library.

### CODE REVIEW

**Comment by wu-sheng** [comment]
What is the new lib license? 
We need to evaluate all licenses of dependencies.

**Comment by jmjoy** [comment]
> What is the new lib license? We need to evaluate all licenses of dependencies.

[MIT ](https://choosealicense.com/licenses/mit)OR [Apache-2.0](https://choosealicense.com/licenses/apache-2.0)

<https://github.com/dtolnay/thiserror#license>

**Comment by jmjoy** [comment]
And the tool `cargo-license` can list all license of dependencies.

image

**Comment by wu-sheng** [comment]
Could you add a CI check to cross check this command result with a hosted file in the repo?
Then we could check no dependencies change in PR, and all dependencies are safe in the ASF.

**Comment by jmjoy** [comment]
Dependencies License check by skywalking-eyes added.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
