### PR TITLE
Add sub components licenses in dist material.

### PR DESCRIPTION
**Pull request by jmjoy**
1. Add dist-material directory and LICENSE, NOTICE, licenses files.
2. Update year of NOTICE.
3. Prost upgrade the mini required rust version without upgrade the minor version, So I have to follow it to update.

### CODE REVIEW

**Review by wu-sheng — COMMENTED** [review]
You don't need to copy Apache 2.0 license, but we need to copy Apache 2.0 notice into our binary notice.

Also, there is a license check CI in the main repo. You may be interested to add a similar one for rust.

**Comment by jmjoy** [comment]
But I don't found NOTICE file in sub component repositories.

**Comment by wu-sheng** [comment]
> But I don't found NOTICE file in sub component repositories.

If you can't, you don't need to copy anything. Just keep the repository name, version, license in the dist/license file. That is enough.(For Apache 2.0 License). For MIT, BSD, etc., you should copy the license files(ignore NOTICE).

**Comment by jmjoy** [comment]
The `license-eye` has a bug when generating the LICNESE file for rust project, so skip the CI checking of `dist-meterial/LICNESE` in this PR?

**Comment by jmjoy** [comment]
There is a problem here. The dependent version specified by `Cargo.toml` is not necessarily the version actually used by the user, but the minimum compatible version, while the summary license lists the exact version number. Is there a problem?

**Comment by wu-sheng** [comment]
> There is a problem here. The dependent version specified by `Cargo.toml` is not necessarily the version actually used by the user, but the minimum compatible version, while the summary license lists the exact version number. Is there a problem?

We just need to list what we need. If users bump up the version, and license changed(sometimes it happens), then it is user's responsibility
So, I think we are good.

**Review by wu-sheng — APPROVED** [review]
Cool, thanks for fixing.

**Pull request merged**
