### PR TITLE
Split tracer inner segment sender and receiver into traits.

### PR DESCRIPTION
**Pull request by jmjoy**
So users can customize the channel inside the tracer, such as using ipc channel.

### CODE REVIEW

**Comment by wu-sheng** [comment]
What is `ipc` channel? Could you provide a case about how to use this?

**Comment by jmjoy** [comment]
> What is `ipc` channel? Could you provide a case about how to use this?

The `ipc` channel can transmit data across processes, which is need in some multi-process architecture services (such as nginx and php-fpm), like in <https://github.com/jmjoy/php-skywalking-agent/blob/705d08e716f80a3f0cad4c2efd211709bf384adb/src/module.rs#L73>.

**Comment by wu-sheng** [comment]
OK, so, you want to propagate collected segments or tracing context, or both?

**Comment by jmjoy** [comment]
> OK, so, you want to propagate collected segments or tracing context, or both?

Only segments.

**Comment by wu-sheng** [comment]
So, generally, you just want one process to report segments? Because this has better perf.?

**Comment by jmjoy** [comment]
> So, generally, you just want one process to report segments? Because this has better perf.?

There is one manager process to report segments to skywalking server via grpc, and multi worker process to handle request, generate segments and transmit to manager process via ipc channel.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
