### PR TITLE
Add logging.

### PR DESCRIPTION
**Pull request by jmjoy**
- [x] Move `Tracer` reporting method to `GrpcReporter`.
- [x] Add `Logger` and `LogRecord` api.
- [x] Add logging integration tests.

### CODE REVIEW

**Comment by jmjoy** [comment]
@wu-sheng It seems that [skywalking-agent-test-tool](https://github.com/apache/skywalking-agent-test-tool) does not support the mock of logging, it should be added to doing e2e for logging?

**Comment by wu-sheng** [comment]
Yes, it should be added.

**Comment by jmjoy** [comment]
[skywalking-agent-test-tool](https://github.com/apache/skywalking-agent-test-tool)
Add logging mock and validation.
https://github.com/apache/skywalking-agent-test-tool/pull/39

**Comment by jmjoy** [comment]
Readme updated.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
